### ISSUE TITLE
uploading dokuwiki-plugin-ie-warning

### ISSUE THREAD

**Issue by simon-mngld** [practical-solutions/dokuwiki-plugin-ie-warning#1]
Had to upload "iewarning" instead of "dokuwiki-plugin-ie-warning" as a folder, as the "-" was not accepted by the Doku-Wiki Plugin Manager. Is there a way to keep the "dokuwiki-plugin-ie-warning" as a official name in github, but be able to download "iewarning" as a folder not to create the error message again? Or is it a well known thing among Dokuwiki users not to upload folders containing "-"? Anyway, my first "action" on github :P

**Comment by practical-solutions** [comment]
Check plugin.info.text -> "iewarning" stated as basefolder, thus you must upload the files into [DOKUWIKI_BASE]/lib/plugins/iewarning/
